### ISSUE TITLE
React 15.6 - Warning on setting css properties

### ISSUE THREAD

**Issue by Azerothian** [Stanko/react-plx#10]
React Version: 15.6.0
React Version: 16 (fails completely)

Message: Warning: a 'div' tag (owner: 'unknown') was passed a numeric string value for CSS property 'background-position-x' (value: '-1.86') which will be treated as a unitless number in a future version of React.

```jsx
<Plx
      className="section-2"
      style={{
        zIndex: 10,
        height: "100vh",
      }}
      parallaxData={[{
        start: ".start-section-2",
        duration: 700,
        name: "first",
        properties: [
          {
            startValue: 0,
            endValue: -50,
            property: "backgroundPositionX",
          }, {
            startValue: 0,
            endValue: -20,
            property: "backgroundPositionY",
          }
        ],
      }]}>
```

**Comment by Stanko** [comment]
Fixed here -> https://github.com/Stanko/react-plx/commit/7cbb7b279718890eee392d2e41dcc28be42c9ceb
