### ISSUE TITLE
All parallax triggers tied to single element

### ISSUE THREAD

**Issue by LinkCable** [Stanko/react-plx#14]
Hi, really appreciate this library.

I'm trying to use it in a project I have, but am encountering this weird this weirdness where the parallax events are all triggered when one element is in view and otherwise do nothing.

Basically I have a component `Project` and it looks something like this:

```
<div>
    <Plx>
        <img/>
    </Plx>
    <Plx>
        <p>description</p>
    </Plx>
</div>
```

Now elsewhere I have my `App` which is like
```
<div>
   <Project />
   <Project />
</div
```

And the first `Project`'s parallax effect only starts when the second one starts i.e. they are in sync. Any advice why this might be?

Thanks.

**Comment by Stanko** [comment]
Hello @LinkCable,
Well if they share configuration that is the expected behavior. Can you please recreate the case here https://codesandbox.io/ so I can take a look

**Comment by LinkCable** [comment]
@Stanko 

I'm using this in my parallaxData
```
 start: '60%',
duration: '10%',
```

Shouldn't those be relative to the respective element?

Will create a codesandbox.

**Comment by Stanko** [comment]
Percentage values are relative to the page, not the element, it is noted in the readme:
> percentage of the total page scroll

**Comment by LinkCable** [comment]
Oh okay, got it. Thanks!

**Comment by LinkCable** [comment]
One more question @Stanko , can offset be a percentage of the page or only fixed pixels?

**Comment by Stanko** [comment]
Unfortunately only pixels for now. I have plans to refactor it, but I'm really busy atm, so I'm not sure when I'll get to it.
