### ISSUE TITLE
Fading in paragraphs similar to Medium article

### ISSUE THREAD

**Issue by oyeanuj** [Stanko/react-plx#16]
Hi @Stanko, I had a quick usage question with the library that I was hoping you could help advice: Similar to [the demo](http://davegamache.com/parallax/) in the [Medium article](https://medium.com/@dhg/parallax-done-right-82ced812e61c), I was looking to fade in text on scroll and then after it reaches at half the viewport, fade it out again.

So, now if I am doing it for a few paragraphs of text, am I correct in understanding that I'd need to put each paragraph inside a `<Plx />` component, each with `parallaxData` arrays with two objects each of `start` (going from 0 opacity to 1 till 50% of the viewport) and `end` (and going from 1 to 0 for the next 50% of the viewport)? If yes, would you recommend any different but more performany way of achieving the same result?

Thank you!

**Comment by Stanko** [comment]
Hey again 🙂 as I mentioned in the other issue, I have a plan to refactor units so it is easier to use stuff relative to element's relative positioning. Not sure when I'll get to it though.

Anyway, I need to catch my plane now. But I'll look into your example in next few days.

**Comment by oyeanuj** [comment]
@Stanko Thank you, looking forward to your feedback on the strategy above, even if a quick response.

**Comment by Stanko** [comment]
https://codesandbox.io/s/5ykox640nl

This is a simple example how you can do it.
