### ISSUE TITLE
Add class when component start value matches

### ISSUE THREAD

**Issue by legnoban** [Stanko/react-plx#19]
Is there a way to set a component inside <Plx/> to have certain bootstrap classes when plx start props matches?

**Comment by Stanko** [comment]
Not sure I understand the question. Plx element accepts `className` and `style` props. Anything inside (`children`) is handled by your application, so you have total control over it.

**Comment by legnoban** [comment]
```
<Plx
    parallaxData={ [
        {
            start: 'top',
            duration: 300,
            properties: [
                {
                    startValue: 1,
                    endValue: 0.2,
                    property: 'opacity',
                }]
        }
        ]}>
    <Navigation/>
</Plx>
```

`<Navigation/>` is on the bottom of the home page. When it reaches on top (by scrolling), I want it to have a `navbar fixed-top navbar `class instead of the change in opacity. I'm not sure if this is related to this project though ^^

**Comment by Stanko** [comment]
Unfortunately this library doesn't really tackle that issue.
