### ISSUE TITLE
Add Boolean `disabled` prop 

### ISSUE THREAD

**Issue by iamgioz** [Stanko/react-plx#20]
Hello @Stanko !
is it possible to add Boolean `disabled` prop to have a possibility switch component off and do not 
update styles during scrolling. it might be useful in case when animation should be disabled for mobile devises or some screen sizes.

**Comment by Stanko** [comment]
Hey @iamgioz,
That is definitely something that I'm going to add in the future. It might take a while as I'm really overwhelmed with other projects.
Cheers!

**Comment by markomarkom** [comment]
https://github.com/Stanko/react-plx/pull/21

**Comment by Stanko** [comment]
@iamgioz I just published a version which has `disabled` prop, but please note that API changed. `start` and `duration` are reworked, and I added `end` property.
