### ISSUE TITLE
Interval issue when using in mobile

### ISSUE THREAD

**Issue by dotansimha** [Stanko/react-plx#23]
Hi @Stanko ,

I am trying to integrate this package in my app, but the performance is super slow, and sometimes the scroll event triggered after 1-2 seconds!

I start to debug it, and I think that in Android/iOS mobile browsers, the `setTimeout` and `setInterval` are disabled during scroll, and not triggered, and it takes about 1 second to the scroll manager to start and fire events...

Related:
* https://bugs.chromium.org/p/chromium/issues/detail?id=570845
* https://developer.telerik.com/featured/scroll-event-change-ios-8-big-deal/

**Comment by Stanko** [comment]
Well, there is not much we can do about browser limitations. But I've just tested my demo on both ios and android, and it seems to be working fine? Can you show me your example?

**Comment by Stanko** [comment]
@dotansimha I've reworked how scroll is handled, can you try running same example with the latest release? Please note that v1 introduced breaking changes, `start` and `duration` are reworked, and `end` prop is introduced.
