### ISSUE TITLE
how to trigger function when plx starts / ends?

### ISSUE THREAD

**Issue by rileylnapier** [Stanko/react-plx#26]
i would like to update a property of a component when the plx starts...  but im not sure if that is possible with this library.

thoughts?

would be neat to have inside parallaxData a function onPlxStart or onPlxEnd or just onPlx that passes information that i can use to update react components?

**Comment by Stanko** [comment]
Hello @rileylnapier,
If you want to change CSS property, you can set it using [included CSS classes](https://github.com/Stanko/react-plx#animation-state-css-classes).

ATM `Plx` doesn't support callbacks. But it is something I want to think about and add sometime in the future.

Cheers!

**Comment by rileylnapier** [comment]
k thanks!  maybe if i find time ill poke around the library and see how easy it would be to do
