### ISSUE TITLE
react-native-web

### ISSUE THREAD

**Issue by gHashTag** [Stanko/react-plx#29]
#### Your library is something I've been looking for a very long time, but unfortunately I do not work with the library  [React Native Web](https://necolas.github.io/react-native-web)
Сan you help solve this problem?
After the component `AppRegistry ` is connected, the scroll disappears
```javascript
import { AppRegistry } from 'react-native'
AppRegistry.registerComponent("MyApp", () => AppComponent)

**Comment by Stanko** [comment]
Hello @gHashTag,
Unfortunately I have no experience with react native, and this library was intended for web (browser) use only.

Cheers!

**Comment by gHashTag** [comment]
In general, you can not connect AppRegistry, it works with the library `react-native-web`
