### ISSUE TITLE
Negative scrolling in Safari

### ISSUE THREAD

**Issue by gHashTag** [Stanko/react-plx#30]
How to disable the negative scrolling in Safari?
Initially, the animation works ahead of time.

![bug mov](https://user-images.githubusercontent.com/6774813/38755295-e399355c-3f6d-11e8-8443-afd28b0aca02.gif)

```javascript
const exampleParallaxData = [
  {
    start: 0,
    end: 300,
    properties: [
      {
        startValue: -500,
        endValue: 100,
        property: "translateX"
      }
    ]
  }
]

const Masters = () => (
  <div style={{ height: 4000 }}>
    <Plx parallaxData={exampleParallaxData}
        style={{
          position: 'fixed',
          bottom: '0vh'
        }}
      >
        <Image source={One} style={{width: 600, height: 600 }} />
    </Plx>
  </div>
)

**Comment by gHashTag** [comment]
Please report here when it will be possible to update the library with the corrected error.

**Comment by Stanko** [comment]
Done in v1.1.2, you can see the commit here https://github.com/Stanko/react-plx/commit/8f9cc91daa0add76337e9c5378ddd835d2d624f5

**Comment by gHashTag** [comment]
Updated, but also an error.
![2018-04-14 12 46 05](https://user-images.githubusercontent.com/6774813/38766940-4145f3b0-3fe2-11e8-84ce-13e0df217c5b.png)

My source project
https://github.com/gHashTag/animate/blob/master/src/components/Masters/index.js

**Comment by Stanko** [comment]
I don't see an error? Can you please create a demo on https://codesandbox.io/ or codepen?
