### ISSUE TITLE
iOS safari: <Plx> contents jump when top bar and bottom bar disappear due to scroll

### ISSUE THREAD

**Issue by dam4222** [Stanko/react-plx#31]
See the video below:

https://www.dropbox.com/s/jmp8o3e3fp8b21h/ScreenRecording_05-29-2018%2020-04-08.MP4?dl=0

**Comment by Stanko** [comment]
Hello @dam4222,
It seems you are using height `100%` or `vh` units, which are relative to the viewport height, which changes when top bar shrinks. Try using fixed height for it, or write fix similar to this one:

https://github.com/Stanko/mobile-chrome-vh-fix/blob/master/mobile-chrome-vh-fix.js

In general this issue has nothing to do with the library itself but iOS. Also please try to provide live example as video is not enough to be able to debug.

Hope that helps!
Cheers!

**Comment by dam4222** [comment]
Thank you so much for your time and help, much appreciated. I will investigate this issue and try to post my solution here.

**Comment by dam4222** [comment]
Removing the fixed height container and using position relative with padding on the top and bottom to create the height allowed me to achieve the same effect without having to use the fixed container. Thanks again for your insight on this.
