### ISSUE TITLE
Negative scroll positions

### ISSUE THREAD

**Issue by PeterKey** [Stanko/react-plx#35]
Problem:
On macOS you can scroll a little further than the actual size of the html document resulting in a rubber effect. This is only implemented in Chrome and Safari, but only produces negative pageYOffset values on Safari, resulting in glitching of the parallactic objects when pageYOffset goes below 0.

Possible Solution:
Without having looked through the code I assume the position tracking is done by pageYOffset lookups. Would it be possible to cap the scroll position at 0, which would save me a lot of workarounds? Or might this feature be useful in some cases?

**Comment by Stanko** [comment]
Hello @PeterKey,
Ah, you are right, I already did it here https://github.com/Stanko/window-scroll-manager but forgot to bump version in Plx. I will release a fix in a few minutes.
Cheers!

**Comment by Stanko** [comment]
@PeterKey actually, which version are you using? This was fixed 3 months ago, try updating version of Plx.

I will still update `window-scroll-manager` and release a patch.

**Comment by PeterKey** [comment]
Yarn tells me I was on 1.3.1 . I've updated to 1.3.2 but my website just broke.

1.3.1 uses window-scroll-manager@0.2.2 and 1.3.2 w-s-m@1.1.0. Did you introduce some breaking changes?

**Comment by PeterKey** [comment]
[Here you go.](https://codesandbox.io/s/olm225lmqq) I forked your example project and simply updated the dependency to 1.3.2. I get the same error message in my project.

**Comment by Stanko** [comment]
Yes, I don't see the problem with plx and negative scroll. Am I missing something? Check the gifs I just recorded:

Chrome:
![jul-12-2018 13-59-47](https://user-images.githubusercontent.com/776788/42631951-fccd8a3c-85db-11e8-94f8-205d49314468.gif)

Safari:
![jul-12-2018 14-02-40](https://user-images.githubusercontent.com/776788/42632044-42a0f4a4-85dc-11e8-91c6-9131179fc106.gif)

**Comment by Stanko** [comment]
Nice! Yes, I see it in Safari now. It is a weird one, I'll check what is going on.

**Comment by Stanko** [comment]
Here it is finally!

Try fixed example in Safari:
https://5kmr527q2n.codesandbox.io/

and here is code (just update version to 1.3.5) https://codesandbox.io/s/5kmr527q2n)

Sorry for the messy turnaround.

Cheers!
