### ISSUE TITLE
support clip-path?

### ISSUE THREAD

**Issue by ettubrutesbro** [Stanko/react-plx#36]
hi, love this! it's very easy to use and the example is great. any thoughts or plans on supporting clip-path as one of the properties? i know it can be interpolated - i did a vanilla JS example with it a few years ago.

**Comment by Stanko** [comment]
Hello @ettubrutesbro,
`clip-path` accepts very wide input:
```
<clip-source>
<basic-shape>
<geometry-box>
  margin-box
  border-box
  padding-box
  content-box
  fill-box
  stroke-box
  view-box
```

And while it is possible to cover all of these cases, it is a really big feature. I don't really have time to implement interpolation for it. But if you want feel free to make a PR with your vanilla interpolation.

Cheers!

**Comment by Stanko** [comment]
I won't be implementing this, as it is out of the scope of the library. Cheers!
