### ISSUE TITLE
showcase

### ISSUE THREAD

**Issue by Manny1806** [Stanko/react-plx#39]
I just finished a 6-month coding bootcamp and used react-plx for my portfolio. I used a Plx element for literally everything haha.

http://alex-widner.surge.sh/

**Comment by Stanko** [comment]
Hello @Manny1806,
Thank you for sharing this, that is a lot of Plx configuration 🙂I really enjoy seeing it in the wild, I'll add it to the readme.
Cheers!

**Comment by Stanko** [comment]
https://github.com/Stanko/react-plx/blob/master/README.md#demo 🎉

**Comment by Manny1806** [comment]
Oh wow, thanks for adding it to the read me Stanko!! Yeah, I bet you didn't expect to see it being used the way I used it lol!
