### ISSUE TITLE
Percentage based start trigger?

### ISSUE THREAD

**Issue by blanck-space** [Stanko/react-plx#4]
In many cases, for example, making columns of a row appear one by one(using opacity), staggered, works great on let's say a 1920x1080 device. But the same configuration makes the boxes appear too soon on a 1388x768 device. Assuming that this row of staggered columns is at the end of a page, on an iPad, due to the huge height, the element id provided would never reach the page top, and hence the columns would never appear all.
On the other hand instead of using ids, if one uses a number, that too is in pixels and would cause really inconsistent animations.
If you could just provide me on some insight on the best way to solve this problem then I wouldn't mind spending my time coding the enhancements and contributing to the library, thanks.

**Comment by Stanko** [comment]
Hello @blanck-space,
I have an idea how this can be done, but I'm kinda tired atm, so I'll get back to you tomorrow.

**Comment by Stanko** [comment]
Hey @blanck-space,

I just added support for percentage values (of the total page scroll). Check updated [readme](https://github.com/Stanko/react-plx#parallaxdata) and [demo](https://stanko.github.io/react-plx/).

Please test it yourself, and we can close the issue.

Commit: https://github.com/Stanko/react-plx/commit/207d1050a790608a5f7d782c3bd724c58ba540a8

**Comment by blanck-space** [comment]
@Stanko, Brilliant. Can't believe how prompt that fix was, keep up the good work. I've something I'm sure you'd like to see but it's sort of private for now, is there a way to email you to show it till it's released?

**Comment by Stanko** [comment]
You are welcome @blanck-space and thank you!

It would be great if you can send it, my email is
stanko / dot / tadic at google's email. Hope you get my try of email obfuscation :)
