### ISSUE TITLE
Visibility: hidden until react-plx load

### ISSUE THREAD

**Issue by drewpc** [Stanko/react-plx#40]
I have an isomorphic application that renders a header with an image + text.  I'm using react-plx to provide a parallax effect where the image and text scroll at different rates.  When my server renders the HTML, the line below from react-plx makes the image + text area not visible until after JS has loaded:

https://github.com/Stanko/react-plx/blob/6019ace4a3f96ac25a3359962054a51e25cf3f93/source/Plx.js#L813

If I disable Javascript on my browser (so that I view the server side rendered HTML only), I would expect the image + text to load and scroll as normal with the page.  Instead, I don't see any image or text and it just looks weird.  I see the same thing on your live demo site: without Javascript turned on in the browser, none of the content loads below the link to Github.

Do you think there's a way to refactor the `showElement` logic so that the content is rendered on page load and then changed when the client takes over?  Or does that cause the page to jump if scrolled?

**Comment by Stanko** [comment]
Hello @drewpc,
There are two problems here:
* render component on server
* prevent jumping of the component when client picks up (when scrol positions isl !== 0)

Visibility fixes the second one. I think it is better user experience for element to show in the correct place then to render it on the wrong one and then make it jump to the correct one.

I will try to find a solution to fix both, by checking if `window` is defined.

For now you can fix this by making a simple wrapper component which will render `div` on server and `Plx` on client.

Something like this:
```js
import React from 'react';
import Plx from 'react-plx';

const PlxWrapper = (props) => {
  const ComponentToRender = IS_SERVER ? 'div' : Plx;
  return (
    <ComponentToRender { ...props } />
  );
};
```

Hope that helps!

**Comment by drewpc** [comment]
Thanks for the work around idea!  I'm curious to see if there's a solution that works in both cases, without having to re-render the entire component as either a `<div/>` or `<Plx/>`.  I'll spend some time looking into that and report back.

**Comment by drewpc** [comment]
@Stanko sorry for the trouble, but could you post the example that you are using to test this issue so I can see the page jump?  On my application, when I comment out this line:

https://github.com/Stanko/react-plx/blob/6019ace4a3f96ac25a3359962054a51e25cf3f93/source/Plx.js#L813

The server side rendered version works great and there's no jump in the page if I'm scrolled further down the page.  Maybe my use of your library is too simple and a more complex example would cause the page to jump?

Thanks!

**Comment by Stanko** [comment]
The first load is the problematic one, once cached it doesn't jump (at least in chrome, I would need to test IEs 🙃). 

I recorded this gif with dev tools and "Disable cache" active, and you can see on refresh, server renders the first frame followed by the jump when client app loads.

![test](https://user-images.githubusercontent.com/776788/45782947-b4bf7d80-bc64-11e8-8d67-34ae0b2bbf58.gif)

Unfortunately, universal rendering is full of problems like this. Probably the best solution is to make that visibility thing optional through props. TBH I'm not a huge fan of adding too many props, but it seems like a only way in this scenario.

Cheers!

**Comment by drewpc** [comment]
Thanks a lot for posting the example.  Your usage does make sense why the visibility should be hidden first.  In my case, my animations are different and I don't need to worry about jumping.  If you don't mind, I'll submit a PR with a prop that makes sense.

**Comment by drewpc** [comment]
Scratch that.  For my purposes, I can set the react-plx prop `disabled: true` on the server side and then `disabled: false` when the client loads (with `componentDidMount()`) and it works great!

**Comment by Stanko** [comment]
Glad you figured it out 🎉  

I totally forgot about `disabled` 🙈  maybe you can just use 
```js
disabled={ typeof window === 'undefined' }
```
then you don't need to handle more component states.

Cheers!

**Comment by AlexandraKlein** [comment]
I was still having some `visibility: hidden;` issues on mount and `disabled={typeof window === 'undefined'}` didn't always solve it.

I had to implement the following:

```javascript
const Component = () => {
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(typeof window !== 'undefined');
  });

  return isMounted ? (
    <Plx parallaxData={parallaxData}>
      <img alt={src} src={src} />
    </Plx>
  ) : (
    <img alt={alt} className={`blvd-home-hero__image`} src={src} />
  );
};
```
