### ISSUE TITLE
Showcase: added react-plx to my portfolio

### ISSUE THREAD

**Issue by dspacejs** [Stanko/react-plx#42]
I wanted to add a nice-looking and simple animation to [my portfolio](https://danieljs.tech), so I added it to the intro section.

Performs well, works great on all devices, and was very easy to setup. Cheers!

**Comment by Stanko** [comment]
Awesome! 🎉 Thank you for sharing, it is always a pleasure to see people using it.
Excuse me for not putting it in the readme, as animation is so subtle that is barely noticeable.
Cheers!
