### ISSUE TITLE
consider adding an API to consume the scroll manager?

### ISSUE THREAD

**Issue by Xie-Hui** [Stanko/react-plx#43]
I'm trying to add the scroll animation for the header navbar and wondering if there is a way to consume the scroll manager to get the current scroll position and do some customize the action accordingly.

**Comment by Stanko** [comment]
Hello @Xie-Hui,
I don't really understand what are you trying to achieve.

[window-scroll-manager](https://github.com/Stanko/window-scroll-manager) is a standalone package if that is what you are looking for.

Cheers!

**Comment by Xie-Hui** [comment]
Hi @Stanko  thanks for the information. I think that's what I need!
