### ISSUE TITLE
Explain how the sticky text works?

### ISSUE THREAD

**Issue by dylancristy** [Stanko/react-plx#45]
I can't seem to get that effect to work.  To get something to stick I have to add a step where it is animating `translateY` in a positive direction, essentially fighting against the natural scroll, and because it is animating it's a bit wiggly.  I'd love to get it to come in and stick and stay stable.

**Comment by Stanko** [comment]
Hello @dylancristy,

I think if you check the source code, it will make it a little bi clearer. There is some trickery between this effect. Element has `position: fixed` it sticks to the bottom, and has `opacity: 0`. Therefore it is always on the screen.

https://github.com/Stanko/react-plx/blob/master/docs/docs.scss#L291-L309

The first parallax block 
https://github.com/Stanko/react-plx/blob/master/docs/sticky-text.js#L6-L21
will fade it in, and move it to the center of the screen. It is not flickering and fighting natural scroll, as `position: fixed` is applied.

At the end, second parallax block moves it out of the screen and fades it out.
https://github.com/Stanko/react-plx/blob/master/docs/sticky-text.js#L22-L39

Hope this helps,
Cheers!

**Comment by dylancristy** [comment]
Got it.  I see now, and I'm able to get a similar effect using `position: fixed`.

Thanks!
