### ISSUE TITLE
Allow animation only trigger once?

### ISSUE THREAD

**Issue by dingcaiying** [Stanko/react-plx#51]
Thanks for making this great library, really like the `parallaxData` option, it's so smart and convenient.

I'm now facing a request to let the parallax effect only runs on first time the element appears, and I find it's not easy with current exposed APIs. Mostly because of there is no easy way to know when does the element firstly fully displayed / visible (my idea is: setting `freeze` to true when element fully display, either when landing or after scrolling). I understand this might not be included in the design of this library, but any advice will be appreciated.

Maybe could consider add this feature?

**Comment by Stanko** [comment]
Hello @dingcaiying,

Thank you for the kind words. I can add a callback which would trigger only once when scroll is below the scroll position of the last animation defined. Based on that you could set your state and pass `freeze={ true }` to Plx. 

But there is a tricky situation here, if the user is already beneath the animation, and refreshes the page, animation would never be played. I would like to avoid adding complex logic to check if all parts of the animation have been shown.

What do you think?
Cheers!

**Comment by dingcaiying** [comment]
Hello @Stanko ,

Regarding the tricky situation you mentioned above, I tried this morning, if I set `animateWhenNotInViewport` to true, then element will have target styling directly (in my case, I have a fade in animation, so it's: opacity: 1). I can rely on this logic to handle that situation, although not very smart but it works 😄 . 

If it's not too bothering and you think it's proper for this library, an extra callback would be nice 😄 . I'm trying to use `onPlxEnd` to detect if parallax animation ended so that I can freeze it, but sometimes it's not called as I expected. For example, when scrolling very fast, sometimes `onPlxEnd` is not called. It seems that this callback is not fit for my request.

There're still other options for me, but would like to make sure if is possible to make it work with current implement. 

Thanks a lot for quick reply and helpful advice !

**Comment by Stanko** [comment]
I forgot about `onPlxEnd` 🙂  if it is not triggering, that's a bug. I'll take a look.

Initially I wanted to avoid callbacks as Plx animations don't have start and end in a traditional animation sense. But user can scroll up and down in the middle of it and skip parts.

Not sure how to name new callback, `pageWasScrolledBelowOnce` 🙃 ?

**Comment by dingcaiying** [comment]
@Stanko Yep, if `onPlxEnd ` not triggering in my case is a bug, then no need bothering to add a new callback. Let me create an example for you to check, probably my way of using it is not good.

**Comment by dingcaiying** [comment]
Hello @Stanko , here's an example: https://codesandbox.io/s/m7wyxywkpy .

The content is in the center of the page, I added two `spacing-section` to make the page long enough. In the content section, there are 2 rows, each row has one image and one text block. For each block, I wrapped it with `Plx` component, so that they appears while scrolling and at different timing.

If scrolling slower, it will work fine, but if faster, then some `onPlxEnd` callback seems will be skipped.

**Comment by Stanko** [comment]
To be honest, for that scenario, something like https://www.npmjs.com/package/react-reveal will probably do the better job. I didn't write Plx with that in mind. So I would advise you to use `react-reveal` or a similar library for now.

I thought a little about callback, and I think I'll add
```js
onPlxEnter
onPlxExit 
onPlxAbove
onPlxBelow
onPlxActive // still thinking about this one
```

That is similar how mouse cursor events are handled, so hopefully it will be intuitive.

Cheers!

**Comment by dingcaiying** [comment]
@Stanko 😂will have a try of another library. I also didn't write that section with this feature in mind too, it was a later added request 🤦‍♀️ 

Anyway, thanks a lot for your time! Looking forward to the new APIs!
