### ISSUE TITLE
strokeColor seems to not work

### ISSUE THREAD

**Issue by mfelmy** [Stanko/react-plx#52]
Dear Stanko,

first of all, thank you very much for this amazing package! I was using it a lot in the past couple of weeks, it gives a really easy and intuitiv way to parallax effects!

Today I was trying to fill the path of a .svg file, but I can't get it to work. I noticed, that when the class changed to active (`class="Plx Plx--active`) no `style` is being applied.

I assume this behaviour is not intended?

Thank you very much for your help.
Malte

**Comment by Stanko** [comment]
Hello @mfelmy and thank you! :)

This is a good catch! It should `stroke` instead of `strokeColor`, my bad.

I will fix and publish it later today.

Cheers!

**Comment by Stanko** [comment]
Here it is :)

Fixed in [1.3.13](https://github.com/Stanko/react-plx/commit/d58b358b2324c57ee87a4a05761641f6344bcd62)

Demo:
https://codesandbox.io/s/wrx3kr7y7

**Comment by mfelmy** [comment]
oh wow, thank you so much (:
