### ISSUE TITLE
Can we toggle a class when scrolling?

### ISSUE THREAD

**Issue by dil25** [Stanko/react-plx#57]
Can we toggle the CSS class when scrolling (scroller event)?

**Comment by Stanko** [comment]
It is already supported:
https://github.com/Stanko/react-plx#animation-state-css-classes

**Comment by dil25** [comment]
Thanks for the reply..can we add our own css class when scrolling dynamically?

**Comment by Stanko** [comment]
Unfortunately not, adding custom class for every possible state feels a little bit over the top.

You can achieve everything using these, and I think the code is very readable:

Example:
```css
.Header.Plx--active { }

.Header.Plx--in-0 { }

.Header.Plx--between-0-and-1 { }

.Header.Plx--below { }
```

And you can name your animation parts and those will be used instead of numbers.

Example:
```css
.Plx--in-slideFromLeft { }

.Plx--between-slideFromLeft-and-fadeOut { }

.Plx--in-fadeOut { }
````
