### ISSUE TITLE
On IPhone when zooming page crash. 

### ISSUE THREAD

**Issue by codebee** [Stanko/react-plx#58]
HI @Stanko Stanko Tadić

Thanks for Nice powerful and wonderful tool. We can do lot of parallax related animation easily.

I faced issue on iphone(ios) when zooming my page is crashing.

I have position fixed few divs and when scrolling I am doing zooming and set opacity to zero to visible other divs with the user scroll.

It works fine with desktop and android but normal scrolling works fine in iphone too. but when user zooming on iphone page crashing.
Do you have any idea?

Thank you very much.
:)

I

**Comment by Stanko** [comment]
Hello @codebee,
Can you please provide me with more info? I have never seen page crashing, so it would me debug. Which version of iOS are you using, which iPhones, is it happening of Safari or some other browser. And if you can,  please create a crashing example at https://codesandbox.io/

It is really hard to figure these things out without a reproducible example.

Are you sure some other lib is not making a page crash?

And please note that I’m traveling atm, and I’m not sure when I’ll have time to get to it.

Cheers!

**Comment by codebee** [comment]
> HI @Stanko Stanko Tadić
> 
> Thanks for Nice powerful and wonderful tool. We can do lot of parallax related animation easily.
> 
> I faced issue on iphone(ios) when zooming my page is crashing.
> 
> I have position fixed few divs and when scrolling I am doing zooming and set opacity to zero to visible other divs with the user scroll.
> 
> It works fine with desktop and android but normal scrolling works fine in iphone too. but when user zooming on iphone page crashing.
> Do you have any idea?
> 
> Thank you very much.
> :)
> 
> I

**Comment by codebee** [comment]
Hi @Stanko 

Ok i will create some sample page and let you know. 

Thanks indeed for your quick response. :)

**Comment by codebee** [comment]
I could fixed the issue by using below css. Issue may be happen due to the content size. I have single page with big images. 

  .ios .Plx.Plx--below:not(.section-scroll-wrapper) {
    display: none;
  }
  .ios .Plx.Plx--above:not(.section-scroll-wrapper) {
    display: none;
  }
  .ios .Plx.Plx--active + .Plx--above {
    display: block;
  }

thanks. :)

**Comment by Stanko** [comment]
Cool, glad you made it. I would still love to see an example, so I can try to solve the possible bug in the library.

If you have a lot of large images it might be too heavy for ios.
