### ISSUE TITLE
TypeScript types missing

### ISSUE THREAD

**Issue by carlosoliveraf** [Stanko/react-plx#61]
Since I couldn't find @types/react-plx, how do I import this to my react project? Any help? thanks!

**Comment by Stanko** [comment]
Unfortunately, types are not the part of the package ATM.

You'll need to create a local type definition file, using `PropTypes` as reference:
https://github.com/Stanko/react-plx/blob/master/source/Plx.js#L834-L897

Feel free to open a PR, I will gladly include it in the repo.

Cheers!

**Comment by carlosoliveraf** [comment]
Thank you! I declared local type and it is working perfectly.

**Comment by sandroweb** [comment]
Please, paste declaration here!!

> Thank you! I declared local type and it is working perfectly.
