### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by Stanko** [Stanko/react-plx#63]
I have to add types, for now they are available here:

```
interface PropertiesItemType {
  startValue: string | number;
  endValue: string | number;
  property: string;
  unit?: string;
}

interface ParallaxDataType {
  start: string | number | SafeHTMLElement;
  startOffset?: string | number;
  duration?: string | number | SafeHTMLElement;
  end?: string | number | SafeHTMLElement;
  endOffset?: string | number;
  properties: PropertiesItemType[];
  easing?: string | array | func;
  name?: string;
}

interface IPlxPros {
  animateWhenNotInViewport?: boolean
  children?: any;
  className?: string;
  disabled?: boolean;
  freeze?: boolean;
  parallaxData: ParallaxDataType[];
  style?: string | number | object;
  tagName?: string;
  onPlxStart?: PropTypes.func;
  onPlxEnd?: PropTypes.func;
}

declare module 'react-plx' {
  declare class Plx extends React.Component<IPlxPros> {
    constructor(props: IPlxPros)
  }
  export = Plx;
}
```

**Comment by talentlessguy** [comment]
thank u :heart: , writing stuff without seeing what options are is tough

looking forward for putting this in a new relese

**Comment by stefanooni** [comment]
@Stanko where do I save this code for it to take effect?

**Comment by Stanko** [comment]
You'll need to set `typeRoots` in your tsconfig and add custom types for Plx.

Check the official documentation here:
* https://www.typescriptlang.org/docs/handbook/2/type-declarations.html#your-own-definitions
* https://www.typescriptlang.org/tsconfig#typeRoots

**Comment by stefanooni** [comment]
> You'll need to set `typeRoots` in your tsconfig and add custom types for Plx.
> 
> Check the official documentation here:
> 
> * https://www.typescriptlang.org/docs/handbook/2/type-declarations.html#your-own-definitions
> * https://www.typescriptlang.org/tsconfig#typeRoots

Thanks, however I am getting several errors:

```
Invalid module name in augmentation. Module 'react-plx' resolves to an untyped module at '/Users/stefandunn/Documents/Development/React Version/node_modules/react-plx/lib/index.js', which cannot be augmented.

A 'declare' modifier cannot be used in an already ambient context.

'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
```

Any idea why?

**Comment by Stanko** [comment]
Added in v2.0.0
