### ISSUE TITLE
Scrolling On IE Edge browser jumping and moving Plx divs

### ISSUE THREAD

**Issue by codebee** [Stanko/react-plx#64]
Nice plugging I applied it to my project and it works well on chrome and FF however when scrolling on IE browser it moving with jumping behavior. Can you please help me to sort this out.

I also included below and tried when scrolling on IE still moving with unexpected jumping behavior. 

import 'core-js/es6/map';
import 'core-js/es6/set';
------------
import smoothscroll from 'smoothscroll-polyfill';
smoothscroll.polyfill();

====================
below are my code  I want to control the div moving speed with the user scrolling. 

{
      start: Number(100),
      end: Number(500),
      properties: [
        {
          startValue: 0,
          endValue: 250,
          property: 'translateY'
        }
      ]
    }

**Comment by Stanko** [comment]
Hello @codebee,
Unfortunately, this is due the nature of Internet Explorer and how it handles wheel event. Plx listens to the scroll events and whenever scroll is changed, it recalculates styles and applies them. As IE is triggering these every 50 or so pixels, animation looks choppy.

There is nothing I can do.

Cheers!
