### ISSUE TITLE
Showcase: <antoniocosentino.com> 

### ISSUE THREAD

**Issue by antoniocosentino** [Stanko/react-plx#67]
Hello @Stanko, first of all thanks for creating such a nice component!
I finally published the new version of my website [antoniocosentino.com](https://antoniocosentino.com/) and I'm using **react-plx** in the following pages:

- Homepage (the moving triangles on scroll)
- [Playlists page](https://antoniocosentino.com/playlists)
- Single project page (i.e. https://antoniocosentino.com/projects/ac-2020 )

In the above-mentioned article I'm also briefly talking about my experience with this component compared to other ones that I tried previously.

Thanks again for the great work :)
Antonio

**Comment by Stanko** [comment]
Sweet! Thank you for sharing this, I'll add it to the readme :)

**Comment by Stanko** [comment]
Added it 🎉 
https://github.com/Stanko/react-plx/blob/master/README.md
