### ISSUE TITLE
I have a page with the same component - the scroll position is always related to the first child

### ISSUE THREAD

**Issue by thomasmorice** [Stanko/react-plx#69]
I have a component that I re-use in different places on the page. Inside this component, I'm using react-plx to change an element inside my component. The scroll position seems to be working only on the first time I'm using my component. 
This means the parallaxData are not working properly, they work for the first child, but scroll position is always 100% for the next childs.. 

Hope it make sense

**Comment by Stanko** [comment]
Hey @thomasmorice 
Can you please create an example on https://codesandbox.io or at least paste the code here so I can take a look.

But if you are using a fixed value or a css class for start/end/duration that might be the problem.

**Comment by thomasmorice** [comment]
Hello @Stanko,

Thanks for your reply, I've made an example, using the same component twice.
If you scroll down the page slowly, you'll see in the console that the `transform` value of the first iteration of my `MyPlxComponent` will start around 0, and translate until the max (300) which should be the case

The second iteration of my component will start close to the max.. Seems like the second iteration has the same data as the first iteration when it's in the viewport.. 

Hope it make sense 🤔 

Here is the sandbox: https://codesandbox.io/s/fancy-lake-9458n?file=/src/components/my-plx-component.js

**Comment by Stanko** [comment]
Thank you for putting the time to create a full working example!

Well, that is actually intended behavior. When you use percentages for start and end, it uses page's maximum scroll. Meaning that 0% is when page is at the top and 100% when the page is scrolled all the way down.

Instead you should use `self` for a start, and `window.innerHeight` for `duration. I created a really simplified example but I think it is close to what you are trying to achieve:
https://codesandbox.io/s/react-plx-demo-4hswl?file=/index.js

`start/end/duration` props are a little bit complicated, so be sure to check the documentation here in the readme https://github.com/Stanko/react-plx#parallaxdata

Hope that helps!

**Comment by thomasmorice** [comment]
I understand, that make sense! 
Thanks a lot for your time and help, now it make more sense!
Really nice work there btw! 🙏
