### ISSUE TITLE
Scroll position on something else than the document?

### ISSUE THREAD

**Issue by badtant** [Stanko/react-plx#7]
Hi,

Can this be used to use the scroll position on any element with scrolling overflow instead of checking the scroll position of the whole document?

**Comment by Stanko** [comment]
Hello @badtant,
ATM it is not possible. It will be trickier to pull of than tracking windows scroll. It would be great if you can look into it and create a PR.

**Comment by badtant** [comment]
There is a plain js version of scrollParent from jQuery UI in this thread:
https://stackoverflow.com/questions/35939886/find-first-scrollable-parent

Might be something to use.

**Comment by JulianJorgensen** [comment]
Great work @Stanko ! There are not a lot of react parallax libraries out there.

As for this feature, I do agree it is somewhat essential. I'll try and look into it at one point. I guess it boils down to using `offsetTop` property on the element.

**Comment by Stanko** [comment]
Closing as `won't fix`
