### ISSUE TITLE
use react-plx inside svg

### ISSUE THREAD

**Issue by Githamza** [Stanko/react-plx#74]
I have an svg converted to react component ( https://react-svgr.com/playground/) I would like to make the plx effect within the svg elements

```
<Plx
parallaxData={parallaxData}
>
<rect
    x={221.84}
    y={115.66}
    width={172.75}
    height={127.53}
    rx={12.56}
    transform="rotate(-180 266.775 178.55)"
    fill="#e5e4de"
/>
<rect
    x={221.84}
    y={115.66}
    width={172.75}
    height={127.53}
    rx={12.56}
    transform="rotate(-180 266.775 178.55)"
    fill="url(#prefix__g)"
/>
</Plx>
```

The `rect` element get hidden because of `plx` div element.

A solution to make plx work on specific elements of svg file ?

**Comment by Stanko** [comment]
Hey,
You should use `tagName` prop, something like this:

```jsx
<svg>
  <Plx tagName='rect' parallaxData={...} />
  <Plx tagName='path' parallaxData={...} />
</svg>
```


Check the example here.
https://codesandbox.io/s/react-plx-demo-forked-kx0g2?file=/index.js

Cheers!

**Comment by Githamza** [comment]
yes thanks ! byt transforme attributes does not work
https://codesandbox.io/s/laughing-kilby-n3p8d?file=/src/App.js

**Comment by Stanko** [comment]
I can see the `rect` element moving, check the gif:
![Oct-15-2020 15-17-54](https://user-images.githubusercontent.com/776788/96131595-ad2d3a00-0ef9-11eb-892b-28cbf29f2d39.gif)

Please note that some CSS properties won't work on SVG elements.

For details check Plx documentation:
https://github.com/Stanko/react-plx#properties

Cheers!

**Comment by Githamza** [comment]
yes but it's not at the same place
<img width="1066" alt="Capture d’écran 2020-10-15 à 15 23 44" src="https://user-images.githubusercontent.com/11578288/96133043-1d888b00-0efb-11eb-8a6f-ec16f0dcf2eb.png">
