### ISSUE TITLE
Strange flipping on mobile-devices while scrolling

### ISSUE THREAD

**Issue by xstable** [Stanko/react-plx#75]
See this video and notice the Image-Flipping in the Background: http://somup.com/cYXe2NID7c

You can check it live at https://easy-car-service.de

It might caused by the way, how Browsers on mobile devices handel "animations" while touching & scrolling.
For me it seems that animation are not run as long as you do an tap&move (means scroll, swipe) event, but only start after release the tapping.

What do you think?

You see an similar behavior at your page : muffinman.io/react-plx. I scroll a bit at my device and stop the scrolling... but if I raise my finger to finish the "tapping", there is a litte jump in the animation: 
http://somup.com/cYXeoVID7s

**Comment by Stanko** [comment]
Hey @xstable,
Indeed, it seems like browser is throttling events for performance.

But I think the problem with the backround is due to the `vh` units used. When you scroll, toolbar shrinks, and the viewport height changes, and the background element changes it's height cause it is using `vh`. Try using fixed pixel value to see if it is still happening. If so, then you can use this https://css-tricks.com/the-trick-to-viewport-units-on-mobile/ to fix the `vh` issue.

Cheers!

**Comment by xstable** [comment]
Ah, yes, you are right. I didn't recognize that the scrollbar could be the cause of the issue here.
I will try to change it and see if it minimize the issue with the animation. 
Thanks for this hint.

**Comment by xstable** [comment]
@Stanko ok, that don't seems to be the cause of the issue. I've changed the values to `px`, but same effect as before appears.

BTW: This behavior doesn't appear at the DEV-Mode of Chrome with CPU-Throttling, but only at my real mobile device. (video still with the `vh` implementation): http://somup.com/cYXfQ2IFAT

**Comment by xstable** [comment]
I figured out the exact cause of this issue.
The background-attachment of the background-image is set to `fixed`.

![react-plx-issue](https://user-images.githubusercontent.com/1778068/98104633-fe946d80-1e96-11eb-82da-b0df12f3feb9.gif)

Any Idea, how to get a fixed image in the background without the flipping?

**Comment by Stanko** [comment]
Nice catch! Maybe you can set the position of the element to be fixed instead?

**Comment by xstable** [comment]
What do you mean with "position of element"? Do you have an example for that?

**Comment by Stanko** [comment]
Set `position: fixed` on the div which has background image set.
