### ISSUE TITLE
 dropped fps

### ISSUE THREAD

**Issue by cgarcia369** [Stanko/react-plx#76]
Does anyone know any way to increase the fps in the animations, I feel that they are very lag.

**Comment by Stanko** [comment]
Check if you are following the common "don't dos" mentioned in the readme

> Still you need to avoid common "don't dos" when making a parallax page:
> 
> * Avoid background-size: cover
> * Don’t animate massive images or dramatically resize them
> * Avoid animating 100 things at once
> * Only use properties that are cheap for browsers to animate - opacity and transform (translate, rotate, skew, scale)

https://github.com/Stanko/react-plx#what-is-this

**Comment by cgarcia369** [comment]
-

**Comment by cgarcia369** [comment]
Thanks¡
