### ISSUE TITLE
Smoother effect using values with more decimals

### ISSUE THREAD

**Issue by HyBDev** [Stanko/react-plx#77]
Hey and thanks for this solution!
It's just the thing I searched for many weeks!
I've an issue and I don't know how to do it with yours. I would like to smooth the transition between the start and the end values by using longer decimals transition values. How could I do it?
Thanks! :)
[image](https://user-images.githubusercontent.com/26486143/105566771-f4e30f00-5cfb-11eb-9379-bdf7901b3a45.png)

**Comment by Stanko** [comment]
For performance reasons values are rounded to two decimal places:
https://github.com/Stanko/react-plx/blob/master/source/Plx.js#L387

Feel free to copy the code and change that one line.
Cheers!

**Comment by HyBDev** [comment]
Thanks! :)
