### ISSUE TITLE
Ability to use viewport units 

### ISSUE THREAD

**Issue by bogdansoare** [Stanko/react-plx#8]
Hey there 👋 
This component looks good, I have only one suggestion.
It would be very useful for responsive layouts where scroll height changes and it's not reliable, if we could use viewport units (vh, vw) for **start**, **duration** and **end**.
Apple is doing something similar 
![screen shot 2017-09-18 at 00 07 30](https://user-images.githubusercontent.com/2750170/30524923-77f97e30-9c05-11e7-9d90-490ced24a522.png)

**Comment by Stanko** [comment]
Hello @bogdansoare,
On the top of my head, you could just use `widow.innerHeight` (or `innerWidth`). So for example if you want for your effect to start on `120vh` and to finish on `200vh` you could pass options like this:

```js
{
  start: window.innerHeight * 1.2,
  duration: window.innerHeight * 0.8,
  properties: [
    // ...
  ],
},
```

I think it is cleaner this way, as if I add support for `vh` units, I would need add conditional check, then parse it, and at the end do the exact same thing with `window.innerHeight`.

Hope it helps!

**Comment by bogdansoare** [comment]
Heelo @Stanko .
Thanks for the response. It's a good idea, the problem that I have with it is that I'm server rendering, and I don't have access to the window object.
Also I think there will be a problem when the window height changes.

**Comment by Stanko** [comment]
`Plx` already handles window resize.

As for the server rendering, you should handle it by passing `SERVER_RENDER` env variable, or just checking window type `typeof window === 'undefined'` and render `Plx` only in that case.

**Comment by bogdansoare** [comment]
Cool, will try it out.
Thank you very much for the example 👍

**Comment by Stanko** [comment]
@bogdansoare I'm going to close this one.
