### ISSUE TITLE
Is there a way to sequence from previous values?

### ISSUE THREAD

**Issue by mosesoak** [Stanko/react-plx#81]
Hi @Stanko thanks for this neat lib, we're using it on a really swishy site that I'll share when it's live in a week or so.

Having some trouble with sequencing multiple items in a data array. For example to make a "bounce" effect I can slide in, then slide back a little bit. The trouble is with setting up the values of the second item or any following items, in relation to the previous one. Is there a way to do that?

e.g. item 1:
```js
    start: 'self',
    duration: '40vh',
    startOffset: '20vh' ,
```
item 2:
```js
    start: 'self',
    startOffset: '60vh',
    duration: '20vh',
```
☝️  here you can see that in the 2nd item I had to use 'self' to trigger as well (is there a way to just specify 'continue'?), then offset all the values where 40 + 20 from first item = 60 offset in 2nd item. Is there a way to 'continue' those values?

Thanks!

**Comment by Stanko** [comment]
Hey @mosesoak,
If I understood correctly, I think you can doing using the `easing` prop. Check [this demo](https://codesandbox.io/s/react-plx-easing-demo-6d74c?file=/index.js) I created and see how the box has a little swing at the start and the end:

To do that, just use cubic bezier easing with control points defined in an array:

```js
    easing: [0.25, -0.5, 1, 2.5],
```

You can play with different values and test them on this website: https://cubic-bezier.com/  Also, there are some built-in easing functions in Plx, check the props [documentation](https://github.com/Stanko/react-plx#parallaxdata) for them.

Let me know if this works, cheers!

**Comment by mosesoak** [comment]
Hey @Stanko thanks but not what I was asking at all. I'll try again:

In your

**Comment by mosesoak** [comment]
Sorry, reply continued:

In your example data you show one object getting 3 data objects applied in sequence, using numbers for start and end.

I tried this but in practice it becomes too hard to sequence the values easily because they're fixed. Like if you do 3 datas for item A, ending at 500, then you start item B at 400 that works, until you change item A to end at 1000, now you have to update all the start/end positions of item B.

The obvious solution is to use a non-numerical start value for item B, which solves it between objects, like 'self' for instance.

The problem now is similar within item B. Let's say it contains 2 datas (it's parralaxData array contains 2 data objects) that need to execute back-to-back _where the end of the first item should also be the start of the second._

Because item 1 now uses 'self', not numbers, what is needed is a way for item 2 to pick up where the item 1 left off. 

Like if item 1 is 'self', duration: '50vh', then item2 needs to have a way for its start trigger to be a 'continue' of item 1.

This would allow for a way to sequence animations tightly on a single object, and then you could change the values in item 1 without needing to do mental math to set up item 2.

Is there a way to create a tight sequence where subsequent items can 'continue' from the previous item in the datas array?

Thanks!

**Comment by mosesoak** [comment]
Okay thanks!
