### ISSUE TITLE
Set fixed position when element is centered?

### ISSUE THREAD

**Issue by mosesoak** [Stanko/react-plx#82]
Hi again @Stanko, how can I determine when an element is centered in the viewport in order to set position:fixed, continue parallaxing stuff horizontally, then release it after a certain scroll amount?

Thanks!

**Comment by Stanko** [comment]
That is straight from the demo:

https://muffinman.io/react-plx/

https://github.com/Stanko/react-plx/blob/master/docs/docs.scss#L291-L313
https://github.com/Stanko/react-plx/blob/master/docs/sticky-text.js

**Comment by mosesoak** [comment]
Gotcha, thanks!
