### ISSUE TITLE
onPlxStart/ onPlxEnd function not running in right moment?

### ISSUE THREAD

**Issue by bennofatius** [Stanko/react-plx#92]
Hi! Thank you for this amazing library! All is working well for me so far, except the function calls at animation start or end. When defining a simple function like this:

            onPlxEnd: sayHi(),

and:

function sayHi() {
console.log('hi')
}

...the function will always get called immediately after loading my page, and never when my animation starts/ ends. Any thoughts a to why this may be?

**Comment by Stanko** [comment]
Hey @bennofatius and thank you for the kind words!

Your code actually calls the function right away, it should be this instead:
```js
{
  onPlxEnd: sayHi,
}
```

When you do `sayHi()` it actually calls the function, logs your message and returns a value (`undefined` in your case, as there is no `return`). That means `onPlxEnd` gets an undefined which is not a function.

Cheers!

**Comment by bennofatius** [comment]
Thank you for your prompt reply!
