### ISSUE TITLE
Possibility to add html <tag> prop back in?

### ISSUE THREAD

**Issue by willhindson** [Stanko/react-plx#93]
Hi! Love this component, the only thing I was a little disappointed to see was that the ability to define a custom tag, such as `<h1>` etc to make things more semantic is no longer possible. I was wondering if there would be a way to add this back in, or if you could explain why it needed to be removed / offer an alternate solution? Thanks!

**Comment by Stanko** [comment]
Hey,
I'm really glad you like the library!

Honestly, I removed the tag prop when I switched to typescript. This is the problematic line:
https://github.com/Stanko/react-plx/blob/v2/src/index.tsx#L78

It is important to allow passing HTML props (i.e. for accessibility) and I have no idea how to implement a typing that would change based on the `tag` prop. I'll check it out, but if you have ideas please let me know. 

As a workaround, you can wrap your animation into `h1`. I'm aware this creates an additional element, but I think it works properly from semantic/accessibility point of view.

Cheers!

**Comment by Stanko** [comment]
I think I have an idea, I'll get back to you soon :)

**Comment by Stanko** [comment]
I added it back in [2.1.0](https://github.com/Stanko/react-plx/commit/242189d43378cd264240e16b2d57b8fbe323824b). It wasn't that hard in the end, I'm glad to have it back.

Here you can see the example:
https://github.com/Stanko/react-plx/blob/v2/docs/docs.tsx#L52-L53

Cheers!

EDIT: Let me know if it works for you, and I would love to see example where are you using `Plx` (and include it in the showcase if you approve).

**Comment by willhindson** [comment]
Wow! That's amazingly quick feedback and updating, I wish I had asked sooner 😅. Thanks so much! 🙏
Just tested quickly and it seems to work perfectly 👍

It's all over these projects :)

[eightdaysin.tokyo](https://eightdaysin.tokyo)
[nyctim.es](https://nyctim.es)
[oslo.observer](https://oslo.observer)

**Comment by Stanko** [comment]
You are welcome! 🙂 

These are great, it is great to see people actually using it 😅! If you don't mind I would love to include them in the readme.

**Comment by willhindson** [comment]
Thanks! Sure, feel free to add them :)
